backend:
  name: github
  repo: ParfaitEGT/site-netlifycms
  branch: main
  site_domain: site-netlifycms.netlify.app
  base_url: https://api.netlify.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Corps", name: "body", widget: "markdown" }

